# Generated by Django 4.2.15 on 2024-09-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('locationType', models.CharField(choices=[('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], max_length=10)),
                ('pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payPer', models.CharField(blank=True, max_length=50, null=True)),
                ('jobType', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Co-op', 'Co-op')], max_length=20)),
                ('description', models.TextField()),
                ('postedDate', models.DateField()),
                ('expireDate', models.DateField()),
                ('applicationInstructions', models.TextField()),
                ('applyLink', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
