# Generated by Django 4.2.15 on 2024-09-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates whether the opportunity is currently active and available.'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='applicationInstructions',
            field=models.TextField(help_text='Instructions on how to apply for the opportunity (e.g., submit resume, fill online form).'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='applyLink',
            field=models.URLField(blank=True, help_text='Link to the job application or company career page.', null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='company',
            field=models.CharField(help_text='The name of the company offering the opportunity.', max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(help_text='Detailed description of the job responsibilities and expectations.'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='expireDate',
            field=models.DateField(help_text='The date when the opportunity expires or is no longer active.'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='id',
            field=models.CharField(help_text='Unique identifier for the opportunity.', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='jobType',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Co-op', 'Co-op')], help_text='Type of employment (e.g., Full-time, Part-time, Internship).', max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='location',
            field=models.CharField(help_text='Physical location of the job (e.g., New York, San Francisco).', max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='locationType',
            field=models.CharField(choices=[('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], help_text='Specify if the opportunity is Remote, On-site, or Hybrid.', max_length=10),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='pay',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The salary or hourly wage for the position. Leave blank if not specified.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='payPer',
            field=models.CharField(blank=True, help_text='The frequency of pay (e.g., per hour, per year). Leave blank if not specified.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='postedDate',
            field=models.DateField(help_text='The date when the opportunity was posted.'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='title',
            field=models.CharField(help_text='The title of the job opportunity (e.g., Software Engineer, Data Analyst).', max_length=255),
        ),
    ]
