# Generated by Django 4.2.15 on 2024-09-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_opportunity_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='applicationInstructions',
            new_name='application_instructions',
        ),
    ]
