# Generated by Django 4.2.15 on 2024-09-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_applicationinstructions_opportunity_application_instructions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name_plural': 'Opportunities'},
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='applyLink',
            new_name='apply_link',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='expireDate',
            new_name='expire_date',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='jobType',
            new_name='job_type',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='locationType',
            new_name='location_type',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='payPer',
            new_name='pay_per',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='postedDate',
            new_name='posted_date',
        ),
    ]
