# Generated by Django 4.2.15 on 2024-09-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_opportunity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='id',
            field=models.CharField(help_text='Unique identifier for the opportunity.', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
