# Generated by Django 4.2.15 on 2024-09-27 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0007_alter_opportunity_id_alter_opportunity_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='posted_by',
            field=models.ForeignKey(help_text='Opportunity posted by user. Auto-filled on save.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
