# Generated by Django 4.2.15 on 2024-09-30 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_opportunity_posted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunitySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(help_text='Skill required for the opportunity.', max_length=255)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='website.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(help_text='Qualification required for the opportunity.', max_length=255)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='website.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.CharField(help_text='Benefit offered for the opportunity.', max_length=255)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='website.opportunity')),
            ],
        ),
    ]
