name: Firebase Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
      - '.github/workflows/functions-deploy.yml'

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install main directory dependencies
      run: npm install

    - name: Install functions directory dependencies
      run: npm install
      working-directory:
        ./functions

    - name: Authenticate with Firebase
      uses: wzieba/Firebase-Action@v2
      with:
        firebase_token: ${{ secrets.FIREBASE_TOKEN }}

    - name: Set Firebase Functions environment variables
      run: |
        firebase functions:config:set myapp.employer_signup_key="${{ secrets.EMPLOYER_SIGNUP_KEY }}"

    - name: Deploy to Firebase
      run: |
        firebase deploy --only functions
