name: Deploy the main branch
on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
      - '.github/workflows/functions-deploy.yml'
jobs:
  main:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate with Firebase
      run: firebase auth:login --token "${{ secrets.FIREBASE_TOKEN }}"

    - name: Set Firebase Function Environment Variable
      run: firebase functions:config:set employer.signup_key="${{ secrets.EMPLOYER_SIGNUP_KEY }}"

    - uses: jsryudev/deploy-firebase-functions@v20.0.1
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: firebase-project-id
        FUNCTIONS_DIR: firebase-functions-directory
